### ISSUE TITLE
Type error from enum that caused by duplicated line in constant.py

### ISSUE THREAD

**Issue by Gyyz** [SEACrowd/seacrowd-datahub#316]
## Describe the bug
I update my folk, and get error when run test `python -m tests.test_seacrowd seacrowd/******`
error as below:
```bash
python -m tests.test_seacrowd seacrowd/sea_datasets/icon/icon.py
Traceback (most recent call last):
  File "/Users/yuz/anaconda3/envs/ani/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/yuz/anaconda3/envs/ani/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/yuz/workspace/seacrowd-datahub/tests/test_seacrowd.py", line 14, in <module>
    from seacrowd.utils.constants import Tasks, TASK_TO_SCHEMA, VALID_TASKS, VALID_SCHEMAS, SCHEMA_TO_FEATURES, TASK_TO_FEATURES
  File "/Users/yuz/workspace/seacrowd-datahub/seacrowd/__init__.py", line 1, in <module>
    from .utils.constants import Tasks
  File "/Users/yuz/workspace/seacrowd-datahub/seacrowd/utils/constants.py", line 39, in <module>
    class Tasks(Enum):
  File "/Users/yuz/workspace/seacrowd-datahub/seacrowd/utils/constants.py", line 70, in Tasks
    ASPECT_BASED_SENTIMENT_ANALYSIS = "ABSA"
  File "/Users/yuz/anaconda3/envs/ani/lib/python3.10/enum.py", line 134, in __setitem__
    raise TypeError('Attempted to reuse key: %r' % key)
TypeError: Attempted to reuse key: 'ASPECT_BASED_SENTIMENT_ANALYSIS'
```
## Steps to reproduce the bug
```python
python -m tests.test_seacrowd seacrowd/sea_datasets/barasa/barasa.py
```
In constant.py file, same line: [line 52](https://github.com/SEACrowd/seacrowd-datahub/blob/4df636ea43bb22f0e45009bac6884276556b3562/seacrowd/utils/constants.py#L52)  **VS**  [line 70](https://github.com/SEACrowd/seacrowd-datahub/blob/4df636ea43bb22f0e45009bac6884276556b3562/seacrowd/utils/constants.py#L70)

## Environment info

- `datasets` version: 2.16.0
- Platform: macOS-14.2.1-arm64-arm-64bit
- Python version: 3.10.13
- `huggingface_hub` version: 0.20.1
- PyArrow version: 14.0.2
- Pandas version: 1.3.5
- `fsspec` version: 2023.10.0

**Comment by sabilmakbar** [comment]
Hi @Gyyz, can you try to pull the main based on PR #315? It should've fixed the issue.
